name = "MixedModelsPlots"
uuid = "3abc995f-47f3-4df8-aaf2-5ae06b481260"
authors = ["Phillip Alday <me@phillipalday.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
